name: epic-stuff
on:
  pull_request:
    types: [opened, reopened]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm -v
      - run: node -v
